import logging
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from app.routers import auth, routes

logging.basicConfig(level=logging.INFO)

app = FastAPI(title="ClimbQuest API")


@app.middleware("http")
async def no_store_except_hashed_assets(request: Request, call_next):
    response = await call_next(request)
    # /assets/* filenames are content-hashed per build (safe to cache forever),
    # but everything else - API responses and index.html - must never be
    # served stale, or a cached index.html can end up referencing a
    # since-deleted hashed asset from a previous build (blank page, 404s).
    if not request.url.path.startswith("/assets/"):
        response.headers["Cache-Control"] = "no-store"
    return response


app.include_router(auth.router)
app.include_router(routes.router)


@app.get("/api/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


# Vercel bundles the whole repo checkout alongside this function (confirmed by
# runtime tracebacks resolving backend/app/*.py), and its own static-asset
# routing didn't pick up files generated by the build hook, so the built React
# app is served directly from here instead of relying on that.
FRONTEND_DIST = Path(__file__).resolve().parent.parent.parent / "frontend" / "dist"

if FRONTEND_DIST.is_dir():
    app.mount("/assets", StaticFiles(directory=FRONTEND_DIST / "assets"), name="assets")

    @app.get("/{full_path:path}")
    def serve_spa(full_path: str) -> FileResponse:
        candidate = FRONTEND_DIST / full_path
        if full_path and candidate.is_file():
            return FileResponse(candidate)
        return FileResponse(FRONTEND_DIST / "index.html")
